# Generated by Django 3.2.4 on 2021-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=250, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Файл'),
        ),
    ]
