# Generated by Django 3.2.4 on 2021-07-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_list', '0002_auto_20210701_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
