# Generated by Django 3.2.4 on 2021-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_list', '0003_remove_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
